### ISSUE TITLE
missing array for content and completion

### ISSUE THREAD

**Issue by alouiscious** [learn-co-curriculum/rack-dynamic-routes-lab#3]
this lab forked without the correct application.rb file content -or- the lab instructions / content are missing.
It required i contact AAQ and request help.
the solution was for AAQ rep to give me the missing array content.

Susan Renée Sims

**Comment by sgharms** [comment]
Hm, this sounds like a bug in Learn. I'll close this and pass this on for diagnostics. Please keep us apprised of whether you encounter this again.
